apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.configsSecretName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "test-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  application.yaml: |
    ver: 0.0.1
    service-name: test-api

    http-server:
      server-host: localhost
      server-port: 8087

    api-key: {{ .Values.apiKey | b64enc }}

    db:
      db-type: postgres
      db-host: postgres-postgresql.{{ .Values.namespace }}.svc.cluster.local
      db-port: 5432
      db-user: postgres
      db-password: CePq49vp34
      db-name: postgres

    keys:
      prv-key-auth: ./auth_keys/test-api.rsa
      pub-key-auth: ./auth_keys/test-api.rsa.pub